<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <IsPackable>false</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <OutputPath>$(ArtifactsDirectory)analyzers\$(Configuration)\</OutputPath>
  </PropertyGroup>

</Project>
