<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>Sample04Server</AssemblyName>
    <RootNamespace>Sample04Server</RootNamespace>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TimeWarp.State" />
    <PackageReference Include="TimeWarp.State.Telemetry" />
    <PackageReference Include="TimeWarp.Mediator.Generators" PrivateAssets="all" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
  </ItemGroup>

</Project>
