#region Purpose
// ActionCatalogSourceGenerator: registry snapshot, opt-in, parameters and defaults, name override,
// permissions/visibility, complex parameter types, and compile check of the generated output.
#endregion

// ReSharper disable InconsistentNaming
namespace ActionCatalogSourceGenerator_;

public class Should_Emit_Single_Entry
{
  public static void Given_One_Cataloged_Action()
  {
    const string Source =
      """
      namespace App;

      using TimeWarp.Mediator;
      using TimeWarp.State;

      public sealed partial class CredentialsState : State<CredentialsState>
      {
        public override void Initialize() { }

        public static class AddPasskeyActionSet
        {
          [CatalogAction(Description = "Add a passkey to the account.")]
          public sealed class Action : IAction
          {
            public Action(string label) { Label = label; }
            public string Label { get; }
          }
        }
      }
      """;

    (GeneratorDriverRunResult runResult, Compilation outputCompilation) = ActionCatalogGeneratorTestDriver.Run(Source);

    ActionCatalogGeneratorTestDriver.CatalogSource(runResult).ReplaceLineEndings().ShouldBe
    (
      """
      // <auto-generated/>
      #nullable enable
      #pragma warning disable CS1591

      [assembly: global::Catalog.Tests.GeneratedActionCatalogProviderAttribute]

      namespace Catalog.Tests
      {
        /// <summary>Actions in this assembly marked with [CatalogAction].</summary>
        internal static class GeneratedActionCatalog
        {
          public static global::System.Collections.Generic.IReadOnlyList<global::TimeWarp.State.ActionCatalogEntry> All { get; } =
            new global::TimeWarp.State.ActionCatalogEntry[]
            {
              new global::TimeWarp.State.ActionCatalogEntry
              (
                name: "Credentials.AddPasskey",
                description: "Add a passkey to the account.",
                permissions: global::System.Array.Empty<string>(),
                visibility: (global::TimeWarp.State.ActionVisibility)1,
                stateType: typeof(global::App.CredentialsState),
                actionType: typeof(global::App.CredentialsState.AddPasskeyActionSet.Action),
                parameters: new global::TimeWarp.State.ActionCatalogParameter[]
                {
                  new global::TimeWarp.State.ActionCatalogParameter("label", typeof(string), true, null, "{\"type\":\"string\"}"),
                },
                inputSchema: "{\"type\":\"object\",\"properties\":{\"label\":{\"type\":\"string\"}},\"required\":[\"label\"],\"additionalProperties\":false}",
                executor: static (store, arguments, cancellationToken) =>
                {
                  global::TimeWarp.State.ActionCatalogArguments.EnsureCount("Credentials.AddPasskey", arguments, 1, 1);
                  global::App.CredentialsState state = store.GetState<global::App.CredentialsState>();
                  return state.AddPasskey(global::TimeWarp.State.ActionCatalogArguments.Get<string>("Credentials.AddPasskey", arguments, 0, "label"), externalCancellationToken: cancellationToken);
                },
                displayName: null
              ),
            };
        }

        internal sealed class GeneratedActionCatalogProviderAttribute : global::TimeWarp.State.ActionCatalogProviderAttribute
        {
          public override global::System.Collections.Generic.IReadOnlyList<global::TimeWarp.State.ActionCatalogEntry> Entries => GeneratedActionCatalog.All;
        }
      }
      #pragma warning restore CS1591

      """.ReplaceLineEndings()
    );
    ActionCatalogGeneratorTestDriver.ShouldCompile(outputCompilation);
  }
}

public class Should_Emit_Nothing
{
  public static void Given_No_Cataloged_Actions()
  {
    const string Source =
      """
      namespace App;

      using TimeWarp.Mediator;
      using TimeWarp.State;

      public sealed partial class CounterState : State<CounterState>
      {
        public override void Initialize() { }

        public static class FetchActionSet
        {
          public sealed class Action : IAction { }
        }
      }
      """;

    (GeneratorDriverRunResult runResult, Compilation outputCompilation) = ActionCatalogGeneratorTestDriver.Run(Source);

    runResult.Results
      .SelectMany(result => result.GeneratedSources)
      .ShouldNotContain(generated => generated.HintName == ActionCatalogSourceGenerator.HintName);
    ActionCatalogGeneratorTestDriver.ShouldCompile(outputCompilation);
  }

  public static void Given_Misplaced_Attribute()
  {
    const string Source =
      """
      namespace App;

      using TimeWarp.State;

      [CatalogAction(Description = "Not an action.")]
      public sealed class Widget { }
      """;

    (GeneratorDriverRunResult runResult, _) = ActionCatalogGeneratorTestDriver.Run(Source);

    runResult.Results
      .SelectMany(result => result.GeneratedSources)
      .ShouldNotContain(generated => generated.HintName == ActionCatalogSourceGenerator.HintName);
  }
}

public class Should_Emit_Multiple_Entries
{
  public static void Given_Several_Cataloged_Actions_Only_Opted_In_Are_Listed_In_Name_Order()
  {
    const string Source =
      """
      namespace App;

      using TimeWarp.Mediator;
      using TimeWarp.State;

      public sealed partial class CounterState : State<CounterState>
      {
        public override void Initialize() { }

        public static class ResetActionSet
        {
          [CatalogAction(Description = "Reset the counter.")]
          public sealed class Action : IAction { }
        }

        public static class FetchActionSet
        {
          public sealed class Action : IAction { }
        }
      }

      public sealed partial class ThemeState : State<ThemeState>
      {
        public override void Initialize() { }

        public static class ToggleActionSet
        {
          [CatalogAction(Description = "Toggle dark mode.")]
          public sealed class Action : IAction { }
        }
      }
      """;

    (GeneratorDriverRunResult runResult, Compilation outputCompilation) = ActionCatalogGeneratorTestDriver.Run(Source);
    string generated = ActionCatalogGeneratorTestDriver.CatalogSource(runResult);

    generated.ShouldContain("name: \"Counter.Reset\"");
    generated.ShouldContain("name: \"Theme.Toggle\"");
    generated.ShouldNotContain("Counter.Fetch");
    generated.IndexOf("Counter.Reset", StringComparison.Ordinal)
      .ShouldBeLessThan(generated.IndexOf("Theme.Toggle", StringComparison.Ordinal));
    generated.ShouldContain("return state.Reset(externalCancellationToken: cancellationToken);");
    ActionCatalogGeneratorTestDriver.ShouldCompile(outputCompilation);
  }
}

public class Should_Describe_Parameters
{
  public static void Given_Defaults_Enums_Nullable_And_Complex_Types()
  {
    const string Source =
      """
      namespace App;

      using TimeWarp.Mediator;
      using TimeWarp.State;

      public enum Priority { Low, High }

      public sealed record Command(string Title);

      public sealed partial class TodoState : State<TodoState>
      {
        public override void Initialize() { }

        public static class AddItemActionSet
        {
          [CatalogAction(Description = "Add a todo item.")]
          public sealed class Action : IAction
          {
            public Action(Command command, Priority priority, System.Guid? listId = null, int count = 1)
            {
              Command = command;
            }
            public Command Command { get; }
          }
        }
      }
      """;

    (GeneratorDriverRunResult runResult, Compilation outputCompilation) = ActionCatalogGeneratorTestDriver.Run(Source);
    string generated = ActionCatalogGeneratorTestDriver.CatalogSource(runResult);

    generated.ShouldContain("new global::TimeWarp.State.ActionCatalogParameter(\"command\", typeof(global::App.Command), true, null, null),");
    generated.ShouldContain("new global::TimeWarp.State.ActionCatalogParameter(\"priority\", typeof(global::App.Priority), true, null, \"{\\\"type\\\":\\\"string\\\",\\\"enum\\\":[\\\"Low\\\",\\\"High\\\"]}\"),");
    generated.ShouldContain("new global::TimeWarp.State.ActionCatalogParameter(\"listId\", typeof(global::System.Guid?), false, \"null\", \"{\\\"type\\\":\\\"string\\\",\\\"format\\\":\\\"uuid\\\"}\"),");
    generated.ShouldContain("new global::TimeWarp.State.ActionCatalogParameter(\"count\", typeof(int), false, \"1\", \"{\\\"type\\\":\\\"integer\\\"}\"),");
    generated.ShouldContain("\\\"command\\\":{\\\"x-clr-type\\\":\\\"App.Command\\\"}");
    generated.ShouldContain("\\\"required\\\":[\\\"command\\\",\\\"priority\\\"]");
    generated.ShouldContain("EnsureCount(\"Todo.AddItem\", arguments, 2, 4);");
    generated.ShouldContain("if (arguments.Length == 2) return state.AddItem(");
    generated.ShouldContain("if (arguments.Length == 3) return state.AddItem(");
    generated.ShouldContain("Get<global::System.Guid?>(\"Todo.AddItem\", arguments, 2, \"listId\")");
    ActionCatalogGeneratorTestDriver.ShouldCompile(outputCompilation);
  }
}

public class Should_Use_Value_Text_For_Verbatim_Parameter_Names
{
  public static void Given_Keyword_Named_Parameter()
  {
    const string Source =
      """
      namespace App;

      using TimeWarp.Mediator;
      using TimeWarp.State;

      public sealed partial class LogState : State<LogState>
      {
        public override void Initialize() { }

        public static class RecordActionSet
        {
          [CatalogAction(Description = "Record an event.")]
          public sealed class Action : IAction
          {
            public Action(string @event) { Event = @event; }
            public string Event { get; }
          }
        }
      }
      """;

    (GeneratorDriverRunResult runResult, Compilation outputCompilation) = ActionCatalogGeneratorTestDriver.Run(Source);
    string generated = ActionCatalogGeneratorTestDriver.CatalogSource(runResult);

    generated.ShouldContain("new global::TimeWarp.State.ActionCatalogParameter(\"event\", typeof(string), true, null,");
    generated.ShouldContain("\\\"event\\\":{\\\"type\\\":\\\"string\\\"}");
    generated.ShouldNotContain("@event\"");
    ActionCatalogGeneratorTestDriver.ShouldCompile(outputCompilation);
  }
}

public class Should_Apply_Attribute_Options
{
  public static void Given_Name_Override_Permissions_And_Visibility()
  {
    const string Source =
      """
      namespace App;

      using TimeWarp.Mediator;
      using TimeWarp.State;

      public sealed partial class CounterState : State<CounterState>
      {
        public override void Initialize() { }

        public static class ResetActionSet
        {
          [CatalogAction(
            Description = "Reset the \"main\" counter.",
            Name = "Counters.ResetAll",
            Permissions = new[] { "counter.write", "admin" },
            Visibility = ActionVisibility.Agent)]
          public sealed class Action : IAction { }
        }
      }
      """;

    (GeneratorDriverRunResult runResult, Compilation outputCompilation) = ActionCatalogGeneratorTestDriver.Run(Source);
    string generated = ActionCatalogGeneratorTestDriver.CatalogSource(runResult);

    generated.ShouldContain("name: \"Counters.ResetAll\",");
    generated.ShouldContain("description: \"Reset the \\\"main\\\" counter.\",");
    generated.ShouldContain("permissions: new string[] { \"counter.write\", \"admin\" },");
    generated.ShouldContain("visibility: (global::TimeWarp.State.ActionVisibility)2,");
    ActionCatalogGeneratorTestDriver.ShouldCompile(outputCompilation);
  }
}

public class Should_Emit_DisplayName
{
  public static void Given_DisplayName()
  {
    const string Source =
      """
      namespace App;

      using TimeWarp.Mediator;
      using TimeWarp.State;

      public sealed partial class CredentialsState : State<CredentialsState>
      {
        public override void Initialize() { }

        public static class LinkMicrosoft365ActionSet
        {
          [CatalogAction(Description = "Link a Microsoft 365 account.", DisplayName = "Link \"Microsoft 365\"")]
          public sealed class Action : IAction { }
        }
      }
      """;

    (GeneratorDriverRunResult runResult, Compilation outputCompilation) = ActionCatalogGeneratorTestDriver.Run(Source);
    string generated = ActionCatalogGeneratorTestDriver.CatalogSource(runResult);

    generated.ShouldContain("name: \"Credentials.LinkMicrosoft365\",");
    generated.ShouldContain("displayName: \"Link \\\"Microsoft 365\\\"\"");
    ActionCatalogGeneratorTestDriver.ShouldCompile(outputCompilation);
  }

  public static void Given_No_DisplayName_Emits_Null_Without_Fallback()
  {
    const string Source =
      """
      namespace App;

      using TimeWarp.Mediator;
      using TimeWarp.State;

      public sealed partial class CredentialsState : State<CredentialsState>
      {
        public override void Initialize() { }

        public static class LinkMicrosoft365ActionSet
        {
          [CatalogAction(Description = "Link a Microsoft 365 account.")]
          public sealed class Action : IAction { }
        }
      }
      """;

    (GeneratorDriverRunResult runResult, Compilation outputCompilation) = ActionCatalogGeneratorTestDriver.Run(Source);
    string generated = ActionCatalogGeneratorTestDriver.CatalogSource(runResult);

    generated.ShouldContain("displayName: null");
    ActionCatalogGeneratorTestDriver.ShouldCompile(outputCompilation);
  }
}

public class Should_Name_By_Convention
{
  public static void Given_State_Without_State_Suffix() =>
    ActionCatalogSourceGenerator.GetDefaultName("Credentials", "AddPasskeyActionSet").ShouldBe("Credentials.AddPasskey");

  public static void Given_State_Suffix() =>
    ActionCatalogSourceGenerator.GetDefaultName("CredentialsState", "AddPasskeyActionSet").ShouldBe("Credentials.AddPasskey");
}
